/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billing;

/**
 *
 * @author Shadow_X
 */
public class BillingSystem extends javax.swing.JFrame {

    String operation;
    String answer;
    double fnum, snum, res;
    
    double fruit = 100;
    double veges = 50;
    double pizza = 200;
    double wafer = 20;
    double biscuit = 10;
    
    /**
     * Creates new form BillingSystem
     */
    public BillingSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtDisplay = new javax.swing.JTextField();
        b8 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        bplus = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        bminus = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        bpdt = new javax.swing.JButton();
        bans = new javax.swing.JButton();
        bdot = new javax.swing.JButton();
        bmod = new javax.swing.JButton();
        bdiv = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        bclear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        bAllClear = new javax.swing.JButton();
        bCalculate = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 700));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setPreferredSize(new java.awt.Dimension(330, 380));
        jPanel1.setLayout(null);

        txtDisplay.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jPanel1.add(txtDisplay);
        txtDisplay.setBounds(20, 20, 290, 60);

        b8.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        b8.setText("8");
        b8.setPreferredSize(new java.awt.Dimension(60, 50));
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        jPanel1.add(b8);
        b8.setBounds(100, 110, 60, 50);

        b7.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        b7.setText("7");
        b7.setPreferredSize(new java.awt.Dimension(60, 50));
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        jPanel1.add(b7);
        b7.setBounds(30, 110, 60, 50);

        b9.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        b9.setText("9");
        b9.setPreferredSize(new java.awt.Dimension(60, 50));
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        jPanel1.add(b9);
        b9.setBounds(170, 110, 60, 50);

        bplus.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        bplus.setText("+");
        bplus.setPreferredSize(new java.awt.Dimension(60, 50));
        bplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bplusActionPerformed(evt);
            }
        });
        jPanel1.add(bplus);
        bplus.setBounds(240, 110, 60, 50);

        b4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        b4.setText("4");
        b4.setPreferredSize(new java.awt.Dimension(60, 50));
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel1.add(b4);
        b4.setBounds(30, 170, 60, 50);

        b5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        b5.setText("5");
        b5.setPreferredSize(new java.awt.Dimension(60, 50));
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        jPanel1.add(b5);
        b5.setBounds(100, 170, 60, 50);

        b6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        b6.setText("6");
        b6.setPreferredSize(new java.awt.Dimension(60, 50));
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        jPanel1.add(b6);
        b6.setBounds(170, 170, 60, 50);

        bminus.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        bminus.setText("-");
        bminus.setPreferredSize(new java.awt.Dimension(60, 50));
        bminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bminusActionPerformed(evt);
            }
        });
        jPanel1.add(bminus);
        bminus.setBounds(240, 170, 60, 50);

        b1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        b1.setText("1");
        b1.setPreferredSize(new java.awt.Dimension(60, 50));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1);
        b1.setBounds(30, 230, 60, 50);

        b2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        b2.setText("2");
        b2.setPreferredSize(new java.awt.Dimension(60, 50));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel1.add(b2);
        b2.setBounds(100, 230, 60, 50);

        b3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        b3.setText("3");
        b3.setPreferredSize(new java.awt.Dimension(60, 50));
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel1.add(b3);
        b3.setBounds(170, 230, 60, 50);

        bpdt.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        bpdt.setText("*");
        bpdt.setPreferredSize(new java.awt.Dimension(60, 50));
        bpdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpdtActionPerformed(evt);
            }
        });
        jPanel1.add(bpdt);
        bpdt.setBounds(240, 230, 60, 50);

        bans.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        bans.setText("=");
        bans.setPreferredSize(new java.awt.Dimension(60, 50));
        bans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bansActionPerformed(evt);
            }
        });
        jPanel1.add(bans);
        bans.setBounds(170, 350, 130, 50);

        bdot.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        bdot.setText(".");
        bdot.setPreferredSize(new java.awt.Dimension(60, 50));
        bdot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdotActionPerformed(evt);
            }
        });
        jPanel1.add(bdot);
        bdot.setBounds(100, 290, 60, 50);

        bmod.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        bmod.setText("%");
        bmod.setPreferredSize(new java.awt.Dimension(60, 50));
        bmod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmodActionPerformed(evt);
            }
        });
        jPanel1.add(bmod);
        bmod.setBounds(170, 290, 60, 50);

        bdiv.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        bdiv.setText("/");
        bdiv.setPreferredSize(new java.awt.Dimension(60, 50));
        bdiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdivActionPerformed(evt);
            }
        });
        jPanel1.add(bdiv);
        bdiv.setBounds(240, 290, 60, 50);

        b0.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        b0.setText("0");
        b0.setPreferredSize(new java.awt.Dimension(60, 50));
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });
        jPanel1.add(b0);
        b0.setBounds(30, 290, 60, 50);

        bclear.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        bclear.setText("CLR");
        bclear.setPreferredSize(new java.awt.Dimension(60, 50));
        bclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bclearActionPerformed(evt);
            }
        });
        jPanel1.add(bclear);
        bclear.setBounds(30, 350, 130, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(60, 53, 330, 420);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setText("Billing System");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(490, 10, 220, 40);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(null);

        jCheckBox1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jCheckBox1.setText("Fruits");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox1);
        jCheckBox1.setBounds(30, 50, 120, 50);

        jCheckBox2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jCheckBox2.setText("Veges");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox2);
        jCheckBox2.setBounds(30, 110, 120, 50);

        jCheckBox3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jCheckBox3.setText("Pizza");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox3);
        jCheckBox3.setBounds(30, 170, 120, 50);

        jCheckBox4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jCheckBox4.setText("Wafer");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox4);
        jCheckBox4.setBounds(30, 230, 120, 50);

        jCheckBox5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jCheckBox5.setText("Biscuit");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox5);
        jCheckBox5.setBounds(30, 290, 120, 50);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("0");
        jPanel2.add(jTextField1);
        jTextField1.setBounds(160, 60, 80, 30);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("0");
        jPanel2.add(jTextField2);
        jTextField2.setBounds(160, 120, 80, 30);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("0");
        jPanel2.add(jTextField3);
        jTextField3.setBounds(160, 180, 80, 30);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("0");
        jPanel2.add(jTextField4);
        jTextField4.setBounds(160, 240, 80, 30);

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("0");
        jPanel2.add(jTextField5);
        jTextField5.setBounds(160, 300, 80, 30);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setMinimumSize(new java.awt.Dimension(630, 630));
        jPanel3.setPreferredSize(new java.awt.Dimension(430, 330));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setText("SGST");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(40, 310, 210, 40);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setText(" Total Cost of items");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(30, 30, 210, 40);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel4.setText("Total Delivery Cost");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(30, 90, 210, 40);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setText("Tolal cost of Milaege");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(30, 150, 210, 40);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel6.setText("CGST");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(40, 250, 210, 40);

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("0");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField6);
        jTextField6.setBounds(340, 30, 140, 31);

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("0");
        jPanel3.add(jTextField7);
        jTextField7.setBounds(340, 90, 140, 31);

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("0");
        jPanel3.add(jTextField8);
        jTextField8.setBounds(340, 150, 140, 31);

        jTextField9.setEditable(false);
        jTextField9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setText("0");
        jPanel3.add(jTextField9);
        jTextField9.setBounds(340, 250, 140, 31);

        jTextField10.setEditable(false);
        jTextField10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("0");
        jPanel3.add(jTextField10);
        jTextField10.setBounds(340, 300, 140, 31);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(280, 20, 500, 380);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(410, 50, 800, 420);

        jPanel4.setLayout(null);

        bAllClear.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        bAllClear.setText("Clear");
        bAllClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAllClearActionPerformed(evt);
            }
        });
        jPanel4.add(bAllClear);
        bAllClear.setBounds(720, 30, 180, 70);

        bCalculate.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        bCalculate.setText("Calculate");
        bCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCalculateActionPerformed(evt);
            }
        });
        jPanel4.add(bCalculate);
        bCalculate.setBounds(930, 30, 180, 70);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setText("Sub Total");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(210, 20, 130, 23);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setText("Tax");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(210, 60, 130, 23);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setText("Total Amount");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(210, 100, 130, 23);

        jTextField11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setText("Rs. 0.00");
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField11);
        jTextField11.setBounds(390, 90, 260, 31);

        jTextField12.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setText("Rs. 0.00");
        jPanel4.add(jTextField12);
        jTextField12.setBounds(390, 10, 260, 31);

        jTextField13.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField13.setText("Rs. 0.00");
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField13);
        jTextField13.setBounds(390, 50, 260, 31);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(60, 500, 1150, 130);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        txtDisplay.setText(txtDisplay.getText() + b8.getText());
    }//GEN-LAST:event_b8ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        txtDisplay.setText(txtDisplay.getText() + b5.getText());
    }//GEN-LAST:event_b5ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        txtDisplay.setText(txtDisplay.getText() + b2.getText());
    }//GEN-LAST:event_b2ActionPerformed

    private void bdotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdotActionPerformed
        if(!txtDisplay.getText().contains(".")){
            txtDisplay.setText(txtDisplay.getText() + bdot.getText());
        }
    }//GEN-LAST:event_bdotActionPerformed

    private void bansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bansActionPerformed
        snum = Double.parseDouble(txtDisplay.getText());
        
        switch(operation){
            case "+": res = fnum + snum;
                       answer = String.format("%.2f", res);
                       txtDisplay.setText(answer);
                       break;
            case "-": res = fnum - snum;
                       answer = String.format("%.2f", res);
                       txtDisplay.setText(answer);
                       break;
            case "*": res = fnum * snum;
                       answer = String.format("%.2f", res);
                       txtDisplay.setText(answer);
                       break;
            case "/": res = fnum + snum;
                       answer = String.format("%.2f", res);
                       txtDisplay.setText(answer);
                       break;
            default: res = fnum % snum;
                       answer = String.format("%.2f", res);
                       txtDisplay.setText(answer);    
        }
    }//GEN-LAST:event_bansActionPerformed

    private void bclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bclearActionPerformed
        txtDisplay.setText("");
    }//GEN-LAST:event_bclearActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        txtDisplay.setText(txtDisplay.getText() + b0.getText());
    }//GEN-LAST:event_b0ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        txtDisplay.setText(txtDisplay.getText() + b7.getText());
    }//GEN-LAST:event_b7ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        txtDisplay.setText(txtDisplay.getText() + b9.getText());
    }//GEN-LAST:event_b9ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        txtDisplay.setText(txtDisplay.getText() + b4.getText());
    }//GEN-LAST:event_b4ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        txtDisplay.setText(txtDisplay.getText() + b6.getText());
    }//GEN-LAST:event_b6ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        txtDisplay.setText(txtDisplay.getText() + b1.getText());
    }//GEN-LAST:event_b1ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        txtDisplay.setText(txtDisplay.getText() + b3.getText());
    }//GEN-LAST:event_b3ActionPerformed

    private void bplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bplusActionPerformed
        fnum = Double.parseDouble(txtDisplay.getText());
        txtDisplay.setText("");
        operation = "+";
    }//GEN-LAST:event_bplusActionPerformed

    private void bminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bminusActionPerformed
        fnum = Double.parseDouble(txtDisplay.getText());
        txtDisplay.setText("");
        operation = "-";
    }//GEN-LAST:event_bminusActionPerformed

    private void bpdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpdtActionPerformed
        fnum = Double.parseDouble(txtDisplay.getText());
        txtDisplay.setText("");
        operation = "*";
    }//GEN-LAST:event_bpdtActionPerformed

    private void bdivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdivActionPerformed
        fnum = Double.parseDouble(txtDisplay.getText());
        txtDisplay.setText("");
        operation = "/";
    }//GEN-LAST:event_bdivActionPerformed

    private void bmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmodActionPerformed
        fnum = Double.parseDouble(txtDisplay.getText());
        txtDisplay.setText("");
        operation = "%";
    }//GEN-LAST:event_bmodActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if(jCheckBox1.isSelected()){
            jTextField1.setEditable(true);
            jTextField1.setText("");
            jTextField1.requestFocus(true);
        }
        else{
            jTextField1.setEditable(false);
            jTextField1.setText("0");
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        if(jCheckBox3.isSelected()){
            jTextField3.setEditable(true);
            jTextField3.setText("");
            jTextField3.requestFocus(true);
        }
        else{
            jTextField3.setEditable(false);
            jTextField3.setText("0");
        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
       if(jCheckBox4.isSelected()){
            jTextField4.setEditable(true);
            jTextField4.setText("");
            jTextField4.requestFocus(true);
        }
        else{
            jTextField4.setEditable(false);
            jTextField4.setText("0");
        }
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void bAllClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAllClearActionPerformed
        
        txtDisplay.setText("");
        jTextField1.setText("0");
        jTextField2.setText("0");
        jTextField3.setText("0");
        jTextField4.setText("0");
        jTextField5.setText("0");
        jTextField6.setText("0");
        jTextField7.setText("0");
        jTextField8.setText("0");
        jTextField9.setText("0");
        jTextField10.setText("0");
        jTextField11.setText("Rs. 0.00");
        jTextField12.setText("Rs. 0.00");
        jTextField13.setText("Rs. 0.00");
        
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
        jCheckBox5.setSelected(false);
        
    }//GEN-LAST:event_bAllClearActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
       if(jCheckBox2.isSelected()){
            jTextField2.setEditable(true);
            jTextField2.setText("");
            jTextField2.requestFocus(true);
        }
        else{
            jTextField2.setEditable(false);
            jTextField2.setText("0");
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        if(jCheckBox5.isSelected()){
            jTextField5.setEditable(true);
            jTextField5.setText(" ");
            jTextField5.requestFocus(true);
        }
        else{
            jTextField5.setEditable(false);
            jTextField5.setText("0");
        }
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void bCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCalculateActionPerformed
        double f = Double.parseDouble(jTextField1.getText()) * fruit;
        double v = Double.parseDouble(jTextField2.getText()) * veges;
        double p = Double.parseDouble(jTextField3.getText()) * pizza;
        double w = Double.parseDouble(jTextField4.getText()) * wafer;
        double b = Double.parseDouble(jTextField5.getText()) * biscuit;
        
        double totalval = f + v + p + w + b;
        double del = totalval * 0.05;
        double mil = del * 0.5;
        
        double subtotal = totalval + del + mil;
        double cgst = subtotal * 0.09;
        double sgst = cgst;
        
        double tax = cgst + sgst;
        double amount = subtotal + tax;
        
        jTextField6.setText(String.format("%.2f", totalval));
        jTextField7.setText(String.format("%.2f", del));
        jTextField8.setText(String.format("%.2f", mil));
        jTextField9.setText(String.format("%.2f", cgst));
        jTextField10.setText(String.format("%.2f", sgst));
        jTextField12.setText(String.format("%.2f", subtotal));
        jTextField13.setText(String.format("%.2f", tax));
        jTextField11.setText(String.format("%.2f", amount));
    }//GEN-LAST:event_bCalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillingSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bAllClear;
    private javax.swing.JButton bCalculate;
    private javax.swing.JButton bans;
    private javax.swing.JButton bclear;
    private javax.swing.JButton bdiv;
    private javax.swing.JButton bdot;
    private javax.swing.JButton bminus;
    private javax.swing.JButton bmod;
    private javax.swing.JButton bpdt;
    private javax.swing.JButton bplus;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField txtDisplay;
    // End of variables declaration//GEN-END:variables
}
